### PR TITLE
Moves private helper types into deserialize impl

### PR DESCRIPTION
**Pull request by cmyr**
Feel free to close if this doesn't make sense, but I find it helpful when doing this to just declare the types in the method where they're used.

### CODE REVIEW

**Comment by simoncozens** [comment]
That’s neat - didn’t know you could do that. Now that I look at those structs, though, there’s an obvious parallelism that could be abstracted into a generic in the same way that GPOSGSUB is.

**Comment by cmyr** [comment]
feel free to close this if you go that route.

**Comment by cmyr** [comment]
(or would you like me to make that change?)

**Comment by simoncozens** [comment]
I’m probably overthinking it for not much actual gain. Let’s do it this way.

**Pull request merged**
