### PR TITLE
Change Win EncodingID to 1

### PR DESCRIPTION
**Pull request by m4rc1e**
This matches fontmake and it's also recommended in the ms spec

> When building a Unicode font for Windows, the platform ID should be 3 and the encoding ID should be 1, and the referenced string data must be encoded in UTF-16BE.

https://docs.microsoft.com/en-us/typography/opentype/spec/name#platform-specific-encoding-and-language-ids-windows-platform-platform-id-3

### CODE REVIEW

**Comment by simoncozens** [comment]
You're right - I read this line of code wrong:

https://github.com/googlefonts/ufo2ft/blob/fe565c837d3eb60e1b9b5c63521e47626e42d2e6/Lib/ufo2ft/outlineCompiler.py#L438

For bonus points we should check if the string contains any characters outside the BMP. Probably something like:

```rust
encodingID : if s.chars().any(|c| c > 0xffff) { 10 } else { 1 } 
```

(untested)

**Comment by m4rc1e** [comment]
Ahh good catch! I'll test your proposed statement now.

**Comment by m4rc1e** [comment]
Thanks for the snippet, I've made some amendments and it seems to be working well.


```
  <name>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
      Copyright 2017 The Exo Project Authors (https://github.com/NDISCOVER/Exo-1.0)
    </namerecord>
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Exo Thin
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      regular
    </namerecord>
    <namerecord nameID="3" platformID="3" platEncID="10" langID="0x409">
      Version 2.000;TINY;Exo 😀-Thin
    </namerecord>
...
```

Just a heads up but there's probably a more idiomatic way to do this. My experience isn't there yet.

**Comment by simoncozens** [comment]
Awesome, thank you!

**Pull request merged**
