### PR TITLE
fontcrunch: Replace Rc<Option> with Option<Rc>

### PR DESCRIPTION
**Pull request by cmyr**
This lets us avoid an allocation in the None case.
Profiling allocations on a sample font, this cuts the
total number of allocations by ~60%.

### CODE REVIEW

**Comment by cmyr** [comment]
I don't have a good sense of how much this helps with runtime performance; I've timed it a bunch and the data is pretty noisy, but it doesn't seem huge? It shouldn't really *hurt*, though.

**Comment by simoncozens** [comment]
Nice, thank you!

**Comment by cmyr** [comment]
I'm also going to dig into actually getting rid of the linked list, will let you know how that goes.

**Comment by simoncozens** [comment]
I ran flamegraph and the real hotspot is the numerical integration stuff - arclength and error measuring. So much so that adding “#[inline]” to the functors gained a 10% improvement.

**Pull request merged**
